# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # ================= CONFIGURAÇÃO GLOBAL =================

  if Vagrant.has_plugin?("vagrant-vbguest")
    # Desativa atualização automática do guest additions.
    config.vbguest.auto_update = false
  end

#Box padrão de todas as vms
  config.vm.box = "debian/bookworm64"

  # Não gerar novas chaves SSH
  config.ssh.insert_key = false

  # Desabilitar guest additions
  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end


  # Trigger para desabilitar DHCP do VirtualBox (Host-Only)
  config.trigger.after :up do |trigger|
    trigger.name = "Desabilitar DHCP do VirtualBox"
    trigger.run = {
      inline: <<-SHELL
        VBoxManage dhcpserver remove --netname HostInterfaceNetworking-vboxnet0 || true
      SHELL
    }
  end

  # ================= SERVIDOR DE ARQUIVOS =================
  config.vm.define "arq" do |arq|
    arq.vm.hostname = "arq.caua.joao.devops"
    arq.vm.network "private_network", ip: "192.168.56.121"

    # Criar e anexar 3 discos de 10GB
    (0..2).each do |x|
    arq.vm.disk :disk, size: "10GB", name: "disk-#{x}"
  end


    arq.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbooks/arq.yml"
      ansible.become = true
      ansible.verbose = "v"
    end
  end

  # ================= SERVIDOR DB =================
  config.vm.define "db" do |db|
    db.vm.hostname = "db.caua.joao.devops"

    db.vm.network "private_network",
      type: "dhcp",
      mac: "0800271A0021"

    db.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbooks/db.yml"
      ansible.become = true
      ansible.verbose = "v"
    end
  end

  # ================= SERVIDOR APP =================
  config.vm.define "app" do |app|
    app.vm.hostname = "app.caua.joao.devops"

    app.vm.network "private_network",
      type: "dhcp",
      mac: "0800272B2100"

    app.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbooks/app.yml"
      ansible.become = true
      ansible.verbose = "v"
    end
  end

  # ================= CLIENTE =================
  config.vm.define "cli" do |cli|
    cli.vm.hostname = "cli.caua.joao.devops"
    cli.vm.network "private_network", type: "dhcp"

    cli.vm.provider "virtualbox" do |v|
      vb.name = "cli-devops"
      vb.memory = 1024
    end

    cli.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbooks/cli.yml"
      ansible.become = true
      ansible.verbose = "v"
    end
  end
end
